# Generated by Django 3.2 on 2021-05-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_auto_20210506_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='applied_users',
        ),
        migrations.RemoveField(
            model_name='project',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_questions',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags_requirement',
        ),
        migrations.RemoveField(
            model_name='project_question',
            name='answered_user',
        ),
        migrations.RemoveField(
            model_name='project_question',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='userattribs',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userattribs',
            name='assigned_project',
        ),
        migrations.RemoveField(
            model_name='userattribs',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='userattribs',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userattribs',
            name='github',
        ),
        migrations.RemoveField(
            model_name='userattribs',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='userattribs',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='userattribs',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='userattribs',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userattribs',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='userattribs',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='userattribs',
            name='user_image',
        ),
        migrations.RemoveField(
            model_name='userattribs',
            name='website',
        ),
        migrations.RemoveField(
            model_name='userattribs',
            name='worth',
        ),
        migrations.AddField(
            model_name='userattribs',
            name='service',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Project_Question',
        ),
    ]
